export const mockDesignations = [
  {
    id: "des-001",
    designationName: "Chief Executive Officer",
    shortName: "CEO",
    level: 1,
    department: "Executive",
    description: "Responsible for overall strategic direction and company leadership.",
    createdAt: "2024-01-12T09:30:00Z",
  },
  {
    id: "des-002",
    designationName: "Chief Technology Officer",
    shortName: "CTO",
    level: 2,
    department: "Technology",
    description: "Oversees technological development and technical teams.",
    createdAt: "2024-02-20T11:15:00Z",
  },
  {
    id: "des-003",
    designationName: "Senior Software Engineer",
    shortName: "Sr. SE",
    level: 5,
    department: "Engineering",
    description: "Designs and develops complex software systems.",
    createdAt: "2024-03-05T14:50:00Z",
  },
  {
    id: "des-004",
    designationName: "Junior Software Engineer",
    shortName: "Jr. SE",
    level: 7,
    department: "Engineering",
    description: "Responsible for implementing features and assisting senior developers.",
    createdAt: "2024-03-18T10:10:00Z",
  },
  {
    id: "des-005",
    designationName: "Human Resources Manager",
    shortName: "HR Manager",
    level: 4,
    department: "HR",
    description: "Manages hiring, onboarding, and employee relations.",
    createdAt: "2024-04-01T08:00:00Z",
  },
  {
    id: "des-006",
    designationName: "Finance Analyst",
    shortName: "FA",
    level: 6,
    department: "Finance",
    description: "Analyzes budgeting, forecasting, and financial data.",
    createdAt: "2024-04-12T13:45:00Z",
  },
  {
    id: "des-007",
    designationName: "Product Manager",
    shortName: "PM",
    level: 4,
    department: "Product",
    description: "Ensures product success from planning to execution.",
    createdAt: "2024-05-03T16:20:00Z",
  },
];

export const mockCourseCategories = [
  {
    id: "cat-001",
    categoryName: "IT & Software",
    description: "Covers programming, networking, cybersecurity, and software technologies.",
    createdAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "cat-002",
    categoryName: "Mechanical Engineering",
    description: "Covers mechanical systems, thermodynamics, robotics, and manufacturing.",
    createdAt: "2024-01-15T11:20:00Z",
  },
  {
    id: "cat-003",
    categoryName: "Electrical Engineering",
    description: "Covers circuits, power systems, embedded systems, and electronics.",
    createdAt: "2024-01-18T08:40:00Z",
  },
  {
    id: "cat-004",
    categoryName: "Business & Management",
    description: "Covers strategy, operations, leadership, and organizational management.",
    createdAt: "2024-01-22T14:10:00Z",
  },
  {
    id: "cat-005",
    categoryName: "Civil Engineering",
    description: "Covers construction, structural analysis, design, and infrastructure.",
    createdAt: "2024-01-28T10:55:00Z",
  },
];

export const mockCourseSubCategories = [
  // IT & Software (cat-001)
  {
    id: "sub-001",
    categoryId: "cat-001",
    name: "Web Development",
    description: "Frontend, backend, and full-stack web technologies.",
    createdAt: "2024-02-01T09:00:00Z",
  },
  {
    id: "sub-002",
    categoryId: "cat-001",
    name: "Data Science",
    description: "Machine learning, AI, statistics, and analytics.",
    createdAt: "2024-02-03T10:30:00Z",
  },
  {
    id: "sub-003",
    categoryId: "cat-001",
    name: "Cybersecurity",
    description: "Ethical hacking, network security, and threat analysis.",
    createdAt: "2024-02-05T12:00:00Z",
  },

  // Mechanical Engineering (cat-002)
  {
    id: "sub-004",
    categoryId: "cat-002",
    name: "Thermodynamics",
    description: "Heat, energy, and power system engineering.",
    createdAt: "2024-02-10T11:00:00Z",
  },
  {
    id: "sub-005",
    categoryId: "cat-002",
    name: "Robotics",
    description: "Design and automation of robotic systems.",
    createdAt: "2024-02-11T09:20:00Z",
  },

  // Electrical Engineering (cat-003)
  {
    id: "sub-006",
    categoryId: "cat-003",
    name: "Embedded Systems",
    description: "Microcontrollers, IoT devices, and firmware development.",
    createdAt: "2024-02-15T13:30:00Z",
  },
  {
    id: "sub-007",
    categoryId: "cat-003",
    name: "Power Systems",
    description: "Electrical grids, transmission, and power distribution.",
    createdAt: "2024-02-17T15:00:00Z",
  },

  // Business & Management (cat-004)
  {
    id: "sub-008",
    categoryId: "cat-004",
    name: "Leadership",
    description: "People management and organizational leadership.",
    createdAt: "2024-02-20T08:40:00Z",
  },
  {
    id: "sub-009",
    categoryId: "cat-004",
    name: "Marketing",
    description: "Branding, digital marketing, and market analysis.",
    createdAt: "2024-02-21T10:10:00Z",
  },

  // Civil Engineering (cat-005)
  {
    id: "sub-010",
    categoryId: "cat-005",
    name: "Structural Engineering",
    description: "Design and analysis of structures and frameworks.",
    createdAt: "2024-02-25T12:50:00Z",
  },
  {
    id: "sub-011",
    categoryId: "cat-005",
    name: "Construction Management",
    description: "Project planning and site supervision.",
    createdAt: "2024-02-26T14:10:00Z",
  },
];

export const mockLanguages = [
  {
    id: "lang-001",
    name: "English",
    code: "en",
    nativeName: "English",
    direction: "ltr",
    createdAt: "2024-01-05T10:00:00Z",
  },
  {
    id: "lang-002",
    name: "Hindi",
    code: "hi",
    nativeName: "हिन्दी",
    direction: "ltr",
    createdAt: "2024-01-06T09:45:00Z",
  },
  {
    id: "lang-003",
    name: "Tamil",
    code: "ta",
    nativeName: "தமிழ்",
    direction: "ltr",
    createdAt: "2024-01-07T11:10:00Z",
  },
  {
    id: "lang-004",
    name: "Telugu",
    code: "te",
    nativeName: "తెలుగు",
    direction: "ltr",
    createdAt: "2024-01-08T12:30:00Z",
  },
  {
    id: "lang-005",
    name: "Malayalam",
    code: "ml",
    nativeName: "മലയാളം",
    direction: "ltr",
    createdAt: "2024-01-09T14:00:00Z",
  },
  {
    id: "lang-006",
    name: "Kannada",
    code: "kn",
    nativeName: "ಕನ್ನಡ",
    direction: "ltr",
    createdAt: "2024-01-10T15:10:00Z",
  },
  {
    id: "lang-007",
    name: "Arabic",
    code: "ar",
    nativeName: "العربية",
    direction: "rtl",
    createdAt: "2024-01-11T10:20:00Z",
  },
  {
    id: "lang-008",
    name: "French",
    code: "fr",
    nativeName: "Français",
    direction: "ltr",
    createdAt: "2024-01-12T09:15:00Z",
  },
  {
    id: "lang-009",
    name: "Spanish",
    code: "es",
    nativeName: "Español",
    direction: "ltr",
    createdAt: "2024-01-13T13:45:00Z",
  },
  {
    id: "lang-010",
    name: "German",
    code: "de",
    nativeName: "Deutsch",
    direction: "ltr",
    createdAt: "2024-01-14T16:00:00Z",
  },
];

export const mockTeamMembers = [
  {
    id: "tm-001",
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    role: "Admin",
    status: "active",
    createdAt: "2024-02-01T09:30:00Z",
  },
  {
    id: "tm-002",
    name: "Neha Verma",
    email: "neha.verma@example.com",
    role: "Manager",
    status: "active",
    createdAt: "2024-02-03T11:10:00Z",
  },
  {
    id: "tm-003",
    name: "Rohit Kumar",
    email: "rohit.kumar@example.com",
    role: "Instructor",
    status: "inactive",
    createdAt: "2024-02-05T14:00:00Z",
  },
  {
    id: "tm-004",
    name: "Priya Iyer",
    email: "priya.iyer@example.com",
    role: "Support",
    status: "active",
    createdAt: "2024-02-07T10:20:00Z",
  },
  {
    id: "tm-005",
    name: "Samuel Mathew",
    email: "samuel.mathew@example.com",
    role: "Instructor",
    status: "suspended",
    createdAt: "2024-02-09T08:45:00Z",
  },
  {
    id: "tm-006",
    name: "Aditi Rao",
    email: "aditi.rao@example.com",
    role: "Content Creator",
    status: "active",
    createdAt: "2024-02-12T12:30:00Z",
  },
  {
    id: "tm-007",
    name: "Vikram Das",
    email: "vikram.das@example.com",
    role: "Manager",
    status: "inactive",
    createdAt: "2024-02-15T16:10:00Z",
  },
  {
    id: "tm-008",
    name: "Meera Pillai",
    email: "meera.pillai@example.com",
    role: "Admin",
    status: "active",
    createdAt: "2024-02-18T09:55:00Z",
  },
  {
    id: "tm-009",
    name: "John Fernandes",
    email: "john.fernandes@example.com",
    role: "Support",
    status: "active",
    createdAt: "2024-02-20T13:00:00Z",
  },
  {
    id: "tm-010",
    name: "Ananya Singh",
    email: "ananya.singh@example.com",
    role: "Instructor",
    status: "inactive",
    createdAt: "2024-02-22T15:40:00Z",
  },
];

export const mokeUsers = [
  {
    id: 1,
    name: "Lal",
    email: "lal@gmail.com",
    phoneNumber: "+91 98765 43210",
  },
  {
    id: 2,
    name: "Rohit Sharma",
    email: "rohit.sharma@gmail.com",
    phoneNumber: "+91 91234 56789",
  },
  {
    id: 3,
    name: "Sneha Iyer",
    email: "sneha.iyer@gmail.com",
    phoneNumber: "+91 99887 66554",
  },
  {
    id: 4,
    name: "Karthik R",
    email: "karthik.r@gmail.com",
    phoneNumber: "+91 90123 45678",
  },
  {
    id: 5,
    name: "Neha Patel",
    email: "neha.patel@gmail.com",
    phoneNumber: "+91 90909 80808",
  },
];
